name: process
on: 
   workflow_dispatch:
   push:
   workflow_run:
      workflows: ["scrape"]
      types:
        - completed       
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - uses: actions/cache@v2
        name: Configure pip caching
        id: cache-pip
        with:
          path: |
            ${{ env.pythonLocation}}/bin/*
            ${{ env.pythonLocation}}/lib/python3.9/site-packages/*
            ~/.npm
          key: ${{ runner.os }}-pip-python3.9-3
          restore-keys: |
            ${{ runner.os }}-pip-python3.9-3
      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install sqlite-utils datasette
            datasette install datasette-publish-vercel
      - name: Run scripts
        run: ./scripts/process.sh
      - name: deploy
        run: ./scripts/deploy.sh
        env:
          REPO_NAME: ${{ github.event.repository.name }}           
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push