name: ci
on:
  workflow_dispatch:
  push:
jobs:
  production:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://selfschool.org    
    steps:
      - uses: actions/checkout@v2
      - name: deploy site to vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PROJECT_NAME: "self-school-${{ github.event.repository.name }}"        
        run: |-
          cp -R . "../${PROJECT_NAME}"
          DEPLOYMENT_URL=$(vercel "../${PROJECT_NAME}" --token ${VERCEL_TOKEN} --prod --confirm)
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"        
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
  development:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://selfschool.vercel.app    
    steps:
      - uses: actions/checkout@v2
      - name: deploy site to vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PROJECT_NAME: "self-school-${{ github.event.repository.name }}"        
        run: |-
          cp -R . "../${PROJECT_NAME}"
          DEPLOYMENT_URL=(vercel"../{PROJECT_NAME}" --token ${VERCEL_TOKEN} --confirm)
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"        
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push    
                  
