name: development
on:
  workflow_dispatch:
  push:
    branches:
      - beta
jobs:
  development:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://selfschool-beta.vercel.app    
    steps:
      - uses: actions/checkout@v2
      - name: deploy site to vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PROJECT_NAME: "selfschool-beta"        
        run: |-
          cp -R . "../${PROJECT_NAME}"
          vercel "../${PROJECT_NAME}" --prod --token ${VERCEL_TOKEN} --confirm
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"        
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push    
                  
