name: scrape
on: 
   workflow_dispatch:  
   schedule:
    - cron:  '6 6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run main flow
        run: ./src/scrape.sh

