name: scrape
on: 
   workflow_dispatch:  
   schedule:
    - cron:  '6 6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: |-
            cd scripts/hello
            npm i
            ./main.sh
      
