name: production
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  production:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://selfschool.org    
    steps:
      - uses: actions/checkout@v2
      - name: deploy site to vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PROJECT_NAME: "selfschool-${{ github.event.repository.name }}"        
        run: |-
          cp -R . "../${PROJECT_NAME}"
          vercel "../${PROJECT_NAME}" --token ${VERCEL_TOKEN} --prod --confirm
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"        
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
                  
